# Generated by Django 3.0.6 on 2020-06-27 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0003_tasks_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='task_priority',
            field=models.IntegerField(choices=[(1, 'Important and Urgent'), (2, 'Urgent'), (3, 'Important'), (4, 'Not Important Nor Urgent')], default=4),
        ),
    ]
